name: Waka Readme
on:
  schedule:
    - cron: "30 18 * * *" # Runs daily at 12am IST
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LINES_OF_CODE: "False"
          SHOW_LANGUAGE: "True"
          SHOW_EDITORS: "True"
          SHOW_OS: "True"
